USE efa9xctqhchjw1xm;
TRUNCATE efa9xctqhchjw1xm.projects;
-- CREATE TABLE projects(
-- 	id INTEGER(10) AUTO_INCREMENT NOT NULL,
--     projectTitle VARCHAR(50) NOT NULL,
--     pic VARCHAR(200) NOT NULL,
--     url VARCHAR(100) NOT NULL,
--     repo VARCHAR(100) NOT NULL,
--     technology VARCHAR(300) NOT NULL,
--     projectDescription VARCHAR(3000) NOT NULL,
--     PRIMARY KEY(id)
-- );
INSERT INTO projects (projectTitle,pic,url,repo,technology,projectDescription)
VALUES
("Gif Site", "assets/images/gifSite.png","https://the-ryan-mobley.github.io/GIF_Site/","https://github.com/The-Ryan-Mobley/GIF_Site","Bootstrap styling framework, Javascript, Jquery, the GIPHY Api","This website utilizes GIPHY’s vast api to allow users to search for gifs using a tag system. 
Users can search for tags which will search for gifs associated with the tag. if the user wants to delete a tag they can just simply click on the tag to delete it. This site also utilizes some modern quality of life concepts such as an infinite scroll and a light/dark theme.
"),
("STRGZR", "assets/images/STRGZR.png","https://the-ryan-mobley.github.io/team-thor-project1/","https://github.com/The-Ryan-Mobley/team-thor-project1","Materialize styling framework Leaflet.js,JQuery,Skymap, and the Open Weather API","This is an app that’s perfect for the hobbyist astronomer. Simply click on the map where you plan on stargazing to see both the nightly weather and star map.,This was our first team project I was the project leader so I spent most of the project linking everyone’s code together; I also worked on the weather api functions, and css styling."),
("Burger Time", "assets/images/burgerTime.png","https://floating-oasis-39732.herokuapp.com","https://github.com/The-Ryan-Mobley/burgerTime","Full-Stack using Node.js Express, MYSQL, Handlebars, Jquery, and the Skeleton CSS framework","A small website demonstrating node’s ability to modify and query sql databases. Users can select to either “eat burger” or “cook It!”; when they do to burger moves to the opposite column and updates the database at the same time. Users can create a new burger by clicking the “add a burger button”; then filling out the form after that the database will update, and the burger will be added to the list. "),
("H-Town Brews","assets/images/brews.png","https://ancient-beach-07931.herokuapp.com/","https://github.com/The-Ryan-Mobley/project2personal","Full-Stack using Node.js Express, Express-Sessions, MYSQL, Handlebars, Jquery, and Materialize","H-Town brews is a site where users can rate and review the numerous craft beers in Houston. Users can search for beers then read their reviews, and average rating. Users can make an account if they want to rate and write reviews. This was a group project, I primarily worked on the database, password encryption, session tracking, routing for the site. I also acted as the team lead; making sure tasks were divided evenly, and that everyone’s code worked together."),
("Today I Scraped","assets/images/TIS.png","https://fast-taiga-02345.herokuapp.com/","https://github.com/The-Ryan-Mobley/newsScrape","Full-Stack using Node.js Express, Axios/ Cherrio for scraping, MongoDB with the Mongoose object modeling tool, and skeleton css","Stuck in an awkward elevator ride and need some slightly interesting facts to make small talk? This website is just for you! this site scrapes to trending section of reddit's 'todayilearned' or TIL subreddit. Avoid all the wierd ads disguised as post, and the pop ups about their app. The site does offer links to both the reddit thread, and the posted link; you can also leave comments by clicking the associated button."),
("Click-React-App","assets/images/CRA.png","https://the-ryan-mobley.github.io/click-react-app/","https://github.com/The-Ryan-Mobley/click-react-app","Serverless using only React and Skeleton css","This website uses react to create a memory style game. The page will display a series of images. When the user clicks an image the images will shuffle. If the user clicks a new image the score will increase, if they pick one of the six previous images they've cli- cked the score will decrase. The goal is to get as high of a score as possible."),
("Boogle","assets/images/boogle.png","https://limitless-garden-74095.herokuapp.com/","https://github.com/The-Ryan-Mobley/boogle","MERN stack MongoDB, Express, React, Nodejs","boogle is a wepsite where you can search for books and save them in a collection to keep track of later. Boogle is very useful for keeping track of multiple books for things like research work. This is a full-stack MERN (mongodb, express, react, node) app that uses the google books api to allow users to curate a collection of books in a mongo database."),
("Rocks-fall", "assets/images/lobbyScreen.png","https://vast-citadel-52957.herokuapp.com/","https://github.com/The-Ryan-Mobley/rocks-fall","MERN stack MongoDB, Express, React, Node.js, with Redux and SocketIo","Rocks-Fall is an app that lets users keep track of their Dungeons and Dragons characters, and the large amount of data needed for them. Users can also chat and host games for their D&D sessions, where they can view other user's characters. This app makes robust use of redux, and the wealth of data required for D&D with over 300 spells for players to use!"),
("Hook Scrape", "assets/images/hookscrape.png","https://powerful-cove-03486.herokuapp.com/","https://github.com/The-Ryan-Mobley/hookScrape","MERN stack MongoDB, Express, React, Node.js. using material UI for the layout","This is an improved version of NewsScrape converted to a MERN stack. I used this project to expand upon the original and to test out recursive components using React Hooks. The main improvement is a greatly expanded chat function with comment and reply threads.");

